name: Jordet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26838
title: Everyone does better when EVERYONE does better
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#333333'
    - '#a0a0a0'
    - '#8661fe'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
